### ISSUE TITLE
Group Policies

### ISSUE THREAD

**Issue by cnglaspie** [NCEAS/oss-fishteam#12]
Working on cleaning up the policy documents in the Google Drive.

**Comment by cnglaspie** [comment]
I think we should all put our names under "Conceived of the idea for the MS" for both manuscripts. Thoughts?

**Comment by aesacco** [comment]
Definitely - we all contributed to the overall idea, so that would logically follow. 

I think we need to all sit down and figure out contribution together. This should be done pretty soon so we can figure out who is expected to do what and then we can get our policy documents filled out together, with everyone allowed to ask questions.

**Comment by cnglaspie** [comment]
Do we want to set aside some time tomorrow or this afternoon to discuss this?

**Comment by ailich** [comment]
@cnglaspie that works for me

**Comment by aesacco** [comment]
I concur

**Comment by aesacco** [comment]
Closing as the group agreed on the text of each policy during the April 12, 2018 phone conference. Thank you for your hard work, Cassie!
